baseURL: "kulysf.github.io"
languageCode: en-us
title: kulyusuf
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Ana Sayfa
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projeler
      url: /projects
      weight: 30
    - identifier: folders
      name: Dosyalar
      url: /folders
      weight: 20
    - identifier: search
      name: Ara
      url: /search
      weight: 60

    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Merhaba👋"
    subtitle: Ben Yusuf Kul
    
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:

    - name: "github"
      url: "https://github.com/kulysf"
    - name: "youtube"
      url: "https://www.youtube.com/@kulyusuf"
    - name: "discord"
      url: "https://discord.gg/H56jRSuHBn"
    - name: "instagram"
      url: "https://www.instagram.com/kulyyusuf/"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
